---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asus.
--- DateTime: 2022/5/25 23:06
---

UIRoot = {}

UIRoot.transform = nil

local prefab = AssetBundleManager:LoadResources("ui_root", "UIRoot", typeof(GameObject))
local go = GameObject.Instantiate(prefab)
if UIRoot.transform == nil then
    UIRoot.transform = go.transform
end

function UIRoot:SetParent(panelTransform)
    panelTransform:SetParent(UIRoot.transform)
    panelTransform.offsetMax = Vector2.Zero
end
