---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asus.
--- DateTime: 2022/6/1 22:20
---

MainPanelModel = {}
MainPanelModel.view = MainPanel

MainPanelModel.playerName = "天璇1"
MainPanelModel.level = 120
MainPanelModel.ID = "ID:114514"

return MainPanelModel
