---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asus.
--- DateTime: 2022/5/23 23:34
---

BasePanel:subClass("MainPanel")

MainPanel.controller = nil
MainPanel.model = nil

function MainPanel:Init(abName, resName)
    self.base.Init(self, abName, resName)
    self.resident = true
    self.controller = MainPanelController
    self.model = self.controller.model
    return self
end

function MainPanel:ViewInit()
    local playerInfoNode = self.panelTransform:Find("LeftTop/playerInfo")
    self.levelNumber = playerInfoNode:Find("levelNumber"):GetComponent(typeof(Text))
    self.name = playerInfoNode:Find("name"):GetComponent(typeof(Text))
    self.ID = playerInfoNode:Find("ID"):GetComponent(typeof(Text))
end

function MainPanel:AfterOpen()
    self.levelNumber.text = self.model.level
    self.name.text = self.model.playerName
    self.ID.text = self.model.ID
end
