---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asus.
--- DateTime: 2022/5/24 0:39
---

--Unity相关
UnityEngine = CS.UnityEngine
GameObject = UnityEngine.GameObject
Transform = UnityEngine.Transform
RectTransform = UnityEngine.RectTransform

Vector3 = UnityEngine.Vector3
Vector2 = UnityEngine.Vector2

UI = UnityEngine.UI
Image = UI.Image
Text = CS.TMPro.TMP_Text
Button = UI.Button
Slider = UI.Slider
Toggle = UI.Toggle
ScrollRect = UI.ScrollRect
