---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asus.
--- DateTime: 2022/5/22 15:44
---

xlua.hotfix(CS.ABTest, "Start", function(self)
    print("Hotfix")
end)

xlua.hotfix(CS.ABTest, "Start", nil)
