---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asus.
--- DateTime: 2022/5/21 12:23
---

--常用的类
require("Object")--面向对象相关
require("SplitTools")--字符串拆分
Json = require("JsonUtility")--Json解析
require("Init/AboutUnity")
require("Init/AboutCustom")

--UI
require("UI/Base/UIRoot")
require("UI/PanelManager")
require("UI/Base/BasePanel")

require("UI/Controller/MainPanelController")

PanelManager:OpenPanel("MainPanel")
