---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asus.
--- DateTime: 2022/6/1 22:07
---

require("UI/View/MainPanel")

MainPanelController = {}
MainPanelController.model = require("UI/Model/MainPanelModel")
MainPanelController.view = MainPanel:Init("main_panel", "MainPanel")
